### ISSUE TITLE
How to convert Panorama Image from single file to multi files?

### ISSUE THREAD

**Issue by ttl1601** [avansel/viewer#5]
I have a file image, I want convert it to multi files to use Multiresolution Panorama.

**Comment by romangrinev** [comment]
You can use a free open-source solution such as Hugin (https://equip.avansel.com/product/hugin).
I'm working on an online tool that lets you convert Panorama Images from a single file to multiresolution files that you can use along with Avansel Viewer. And with your support, it will be available for testing soon.

**Comment by GulshanJhaWSP** [comment]
Hi @romangrinev , I also want to achieve same results, looking forward to your online tool for converting equirect to multires :)

**Comment by romangrinev** [comment]
Thank you for your comment @GulshanJhaWSP. I will try to find time to make it work. Thanks again

**Comment by romangrinev** [comment]
So here is the website where you can convert a single panorama file in equidistant projection to a multiresolution panorama files that you can use with Avansel Viewer: https://virturos.com/
1. Open the website and sign up (create a free account). 
2. Click the Upload Panorama Link and upload a single panorama file in equidistant projection.
3. Wait while it is processing then use the Download link on the uploaded panorama to download files you can use for your multiresolution panoramas.

**Comment by romangrinev** [comment]
Here is the example for the multiresolution panorama that has been processed using the website. 
https://virturos.com/panoramas/82
